name: VPC peering module
on: [push]

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: terraform init

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      
      - name: Setup Terraform 
        uses: actions/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


      - name: Check out repository
        uses: actions/checkout@v3


      - name: Terraform plan
        run: terraform plan